### ISSUE TITLE
Regression with 3.9.x firmware and 1.51.0+

### ISSUE THREAD

**Issue by bdraco** [pyenphase/pyenphase#127]
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/enphase_envoy/coordinator.py", line 148, in _async_update_data
    envoy_data = await envoy.update()
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyenphase/envoy.py", line 337, in update
    await self.probe()
  File "/usr/local/lib/python3.11/site-packages/pyenphase/envoy.py", line 320, in probe
    if updater_features := await klass.probe(supported_features):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyenphase/updaters/meters.py", line 89, in probe
    if meter["state"] == CtState.ENABLED:
       ~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by catsmanac** [comment]
so it got an empty reply back?
