### ISSUE TITLE
ReadTheDocs build errors out on No module named 'myst_parser'

### ISSUE THREAD

**Issue by catsmanac** [pyenphase/pyenphase#147]
**Describe the bug**

[Builds since 2 months ago on ReadTheDocs](https://readthedocs.org/projects/pyenphase/builds/) throw an error 

```txt
ModuleNotFoundError: No module named 'myst_parser'
```
when building the pyenphase documentation

**To Reproduce**
Use [Build](https://readthedocs.org/projects/pyenphase/builds/) on Readthe docs

**Additional context**

[last successfull build.log](https://github.com/pyenphase/pyenphase/files/14804839/last.successfull.build.log)

[Last failed build.log](https://github.com/pyenphase/pyenphase/files/14804840/Last.failed.build.log)

Failed log shows myst-parser is being installed

```txt
  - Installing myst-parser (2.0.0)



Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyenphase/envs/latest/lib/python3.11/site-packages/sphinx/registry.py", line 447, in load_extension
    mod = import_module(extname)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/.asdf/installs/python/3.11.6/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'myst_parser'

```

Pyenphase configuration files haven't changed to my knowledge.

Local build in my dev environment,fwiw, have no issue.

**Comment by catsmanac** [comment]
[Log file](https://beta.readthedocs.org/projects/pyenphase/builds/24007317/) shows myst-parser get's installed

```
Skipping virtualenv creation, as specified in config file.
Installing dependencies from lock file

  - Installing myst-parser (2.0.0)


python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
Running Sphinx v7.2.6

Could not import extension myst_parser (exception: No module named 'myst_parser')
```
Installed but not available. Some issue with virtual environments?

Should we change 
```py
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create true
 ```
to false?

**Comment by catsmanac** [comment]
Setting `virtualenvs.create true` did not solve the issue. (https://readthedocs.org/projects/pyenphase/builds/24061834/)

```txt
poetry config virtualenvs.create true
```
is shown by the build, so it used the new one.

It installed myst parser
```
Creating virtualenv pyenphase-A-_cRjsQ-py3.11 in /home/docs/.cache/pypoetry/virtualenvs
Installing dependencies from lock file

  - Installing myst-parser (2.0.0)
```

but spit the same error
```
ModuleNotFoundError: No module named 'myst_parser'
```

**Comment by catsmanac** [comment]
Updated dependencies in #153 did not solve the RTD build issue. Leaves #152 to try.

**Comment by catsmanac** [comment]
#152 solved the issue :-).
